version: "3.7"

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.44.0
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: docker.io/grafana/grafana:9.5.2
    container_name: grafana
    network_mode: host
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:Z
      - ./inventory-service-dashboard.json:/etc/grafana/provisioning/dashboards/inventory-service-dashboard.json:Z
      - ./dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:Z
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  jaeger-all-in-one:
    image: docker.io/jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP receiver
