---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 54df42455c03fbcb6d0e4f50d81af62612a325cc
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 14:56:34 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8083"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: inventory-service
spec:
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 54df42455c03fbcb6d0e4f50d81af62612a325cc
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 14:56:34 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8083"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.15.1
        app.quarkus.io/commit-id: 54df42455c03fbcb6d0e4f50d81af62612a325cc
        app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
        app.quarkus.io/build-timestamp: 2024-10-17 - 14:56:34 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8083"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/quarkus-in-action/inventory-service:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: inventory-service
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
            - containerPort: 8083
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 54df42455c03fbcb6d0e4f50d81af62612a325cc
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 14:56:34 +0000
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: inventory-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  endpoints:
    - scheme: http
      targetPort: 8083
      path: /q/metrics
      interval: 10s
      honorLabels: true
