---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 840a7920d532abc73a000d0ef67fe7b09ecdb5da
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 16:57:48 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8083"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: inventory-service
spec:
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: openjdk-21
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-21
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 840a7920d532abc73a000d0ef67fe7b09ecdb5da
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 16:57:48 +0000
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: inventory-service
spec:
  dockerImageRepository: quay.io/quarkus-in-action/inventory-service
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 840a7920d532abc73a000d0ef67fe7b09ecdb5da
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 16:57:48 +0000
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: inventory-service
spec:
  output:
    to:
      kind: ImageStreamTag
      name: inventory-service:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-21:1.20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 840a7920d532abc73a000d0ef67fe7b09ecdb5da
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 16:57:48 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8083"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: inventory-service
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-uri: <<unknown>>
        app.quarkus.io/quarkus-version: 3.15.1
        app.quarkus.io/commit-id: 840a7920d532abc73a000d0ef67fe7b09ecdb5da
        app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
        app.quarkus.io/build-timestamp: 2024-10-17 - 16:57:48 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8083"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
        - env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:mysql://mysql:3306/inventory
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: quay.io/quarkus-in-action/inventory-service:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: inventory-service
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
            - containerPort: 8083
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/commit-id: 840a7920d532abc73a000d0ef67fe7b09ecdb5da
    app.quarkus.io/vcs-uri: https://github.com/xstefank/quarkus-in-action.git
    app.quarkus.io/build-timestamp: 2024-10-17 - 16:57:48 +0000
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: inventory-service
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: inventory-service
